name: Stable release
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - run: npm install

    - name : version
      run: echo "::set-output name=version::$(node version.js)" 
      id: version

    - name : version name
      run: echo "::set-output name=version-name::$(node version.js true)" 
      id: version-name

    - name: build
      run: npm run build

    - name: rename build
      run: mv dist/BubbleUI.css dist/BubbleUI-v${{ steps.version.outputs.version }}.css

    - name: Create a Release of commit
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ github.token }}
        automatic_release_tag: v${{ steps.version.outputs.version }}
        prerelease: false
        title: ${{ steps.version.outputs.version }} - ${{ steps.version-name.outputs.version-name }}
        files: |
          LICENSE
          dist/*.css
